language: c
sudo: false

env:
    - CFLAGS=-m32 LDFLAGS=-m32
    - CFLAGS=-m64 LDFLAGS=-m64

compiler:
    - clang
    - gcc

after_success:
    - make check || exit 1
    - make distcheck || exit 1

before_script:
    - ./install_libspotify.sh
    - autoreconf -ivs

script:
    - export PKG_CONFIG_PATH=$HOME/libspotify/lib/pkgconfig
    - ./configure
    - make

addons:
    apt:
        packages:
            - check
            - libfuse-dev
            - libglib2.0-dev
            - check:i386
            - libfuse-dev:i386
            - libglib2.0-dev:i386
            - libc6:i386
            - libgcc1:i386
            - gcc-4.6-base:i386
            - gcc-multilib

notification:
    email:
        - anton.lofgren@gmail.com
